<a href="https://colab.research.google.com/github/manuelantelo/03MAIR-Algoritmos-de-Optimizacion/blob/master/Seminario/Seminario_Algoritmos_Manuel_Vicente_Antelo_Santos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algoritmos de optimización - Seminario<br>
Nombre y Apellidos: **MANUEL VICENTE ANTELO SANTOS** <br>
Url Colab: https://colab.research.google.com/drive/1FQvAEoo4LoVWljHnQPjOpVTl603qhuce

Url GitHbub: https://github.com/manuelantelo/03MAIR-Algoritmos-de-Optimizacion/blob/master/Practica/Seminario_Algoritmos_Manuel_Vicente_Antelo_Santos.ipynb<br>
Problema:
> 1. Sesiones de doblaje <br>

Descripción del problema: Organizar sesiones de doblaje
* Se precisa coordinar el doblaje de una película. Los actores de doblaje deben coincidir en las tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actos de doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio de grabación independientemente del número de tomas que se graven. No es posible grabar más de 6 tomas por día. El objetivo es planificar las sesiones por día de manera que el gasto por los servicios de los actores de doblaje sea el menor posible.
  
* Los datos son:
  - Nº de actores = 10
  - Nº de tomas = 30
  - Matriz binaria de participación: A[i][j] = 1 si el actor j participa en la toma i.
  - Una toma puede grabarse un solo día.
  - Cada actor cobra una única vez por día, sin importar las tomas.
  - No se pueden grabar más de 6 tomas por día.
  -

* Objetivo: organizar las sesiones (días de grabación) para minimizar el coste total actor/día; es decir, minimizar el número de veces que los actores deben acudir al estudio ya que "los actores cobran lo mismo por cada día que se desplazan al estudio, indendientementel del nº de tomas que hagan".


**Modelado del problema**
Se representa la participación de los actores mediante una matriz binaria A[i][j]:
 - Filas: tomas (de 0 a 29).
 - Columnas: actores (de 0 a 9).

Técnica aplicada: **Programación entera binaria con restricciones (implementada mediante heurística voraz + mejora local por intercambio de variable)**
* Fase 1 (heurística voraz):
  - Se asignada cada toma al día que implique convocar al menor número de actores nuevos teniendo en cuenta que tiene un máximo de 6 tomas y se eligirá el día con menor coste.
    Esta decisión es localmente óptima y se toma en base a la diferencia de conjuntos: actores_nuevos = actores_toma - actores_ya_convocados_en_dia

* Fase 2 (mejora por intercambio):
  - Con la solución inicial se intenta intercambiar tomas entre pares de dias para ver si el intercambio de variable reduce el total de actores convocados y se aceptaría repitiéndose hasta no encontrar mejoras.


In [ ]:
# Poner aquí el código

In [ ]:
# Poner aquí el código

In [ ]:
# Poner aquí el código

In [ ]:
# Poner aquí el código

In [ ]:
# Poner aquí el código

(*)¿Cuantas posibilidades hay sin tener en cuenta las restricciones?<br>
- Por cada una de las 30 tomas se tiene 6 opciones que son los días posibles.
  Entonces: $6^{30}$ = 221 mil billones de combinaciones posibles


¿Cuantas posibilidades hay teniendo en cuenta todas las restricciones.
- Las restribuciones son:
  
  a) Cada día puede contener como máximo 6 tomas y cada toma debe ser asignada a exactamente un día.

  b) total de días utilizados puede ser ≤ 6.

Buscamos calcular todas las formas posibles de repartir 30 tomas en 6 días con la condición de que cada tía tenga exactamente 6 tomas.

Entonces: $\frac{30!}{(6!)^6} \approx 1{,}896 \times 10^{15}$ posibilidades = **1.9 mil billones** de repartir las 30 tomas en 6 días cumpliendo las restricciones impuestas.
   
Conclusión:
Este problema no es viable usando un algoritmo de fuerza bruta.


Respuesta

Modelo para el espacio de soluciones<br>
(*) ¿Cual es la estructura de datos que mejor se adapta al problema? Argumentalo.(Es posible que hayas elegido una al principio y veas la necesidad de cambiar, arguentalo)


El espacio de soluciones representa el conjunto de todas las configuraciones posibles que cumplen las restricciones del problema.
Durante la primera fase debemos realizar un modelo del problema a resolver.

El espacio de soluciones lo forman todas las posibles asignaciones válidas, y la solución óptima es aquella que minimiza o maximiza una función objetivo bajo esas restricciones.

La solución es una forma de distribuir las 30 tomas en 6 días (con máximo 6 tomas por día), respetando:
 - Cada toma asignada una única vez.
 - Cada día con máximo 6 tomas.
 - Se busca minimizar el coste actor/día.

El espacio de soluciones es el conjunto de todas las particiones posibles del conjunto {0, 1, ..., 29} (30 tomas), en 6 subconjuntos disjuntos de tamaño ≤ 6, donde la unión de todos los subconjuntos cubra todas las tomas sin repeticiones.

Se define como: $$
S = \left\{ (D_1, D_2, \ldots, D_6) \mid D_i \subseteq \{0, \ldots, 29\},\ \bigcup D_i = \{0, \ldots, 29\},\ |D_i| \leq 6,\ D_i \cap D_j = \emptyset \text{ si } i \ne j \right\}
$$

La estructura más adecuada para representar la solución fue usar una "lista de listas" y no tuve necesidad de cambiar por los algoritmos que he usado.
Ventajas:
a) Cada sublista representa un día lo que facilita el cumplimiento de restricciones y la evaluación eficiente del coste actor/día así como contiene los índices de las tomas asignadas a ese día.
b) Es más fácil mover las tomas entre días, el intercambio de variables en las sublistas así como clonarlas.
c) Se calcula rápidamente los actores involucrados en cada día a partir de las tomas asignadas. Ejemplo np.where(SESIONES[toma] == 1)[0])

El manual de la asignatura sugiere que, para problemas de asignación, debemos construir representaciones estructuradas, modificables y evaluables rápidamente, especialmente si aplicamos técnicas heurísticas o metaheurísticas.



Según el modelo para el espacio de soluciones<br>
(*)¿Cual es la función objetivo?
La función objetivo consiste en ***minimizar el número total de actores/día**.

Dimensiones:
- (30 tomas x 10 actores)
- $A[t][a] = 1$ : el actor $a$ participa en la toma $t$  
- $A[t][a] = 0$ : el actor $a$ **no** participa en la toma $t$


Dado un vector de 6 días:

$$(D_1, D_2, \ldots, D_6)$$

y una matriz binaria $A \in \{0, 1\}^{30 \times 10}$, donde:

$$A[t][a] = 1 \quad \text{si el actor } a \text{ participa en la toma } t$$

La función objetivo $f$ se define como:

$$f(D_1, \ldots, D_6) = \sum_{i=1}^{6} \left| \bigcup_{t \in D_i} \text{actores}(t) \right|$$

Es decir, la suma del número de actores distintos convocados en cada día.

Para cada día $D_i$, se calcula el conjunto de actores distintos que participan en las tomas asignadas a ese día luego se suma el número de actores distintos convocados para ese día y como resultado se obtiene el **coste total del actor/día**

La **función objetivo** del modelo para el espacio de soluciones es: $$\min \sum_{i=1}^{6} \left| \bigcup_{t \in D_i} \text{actores}(t) \right|$$

(*)¿Es un problema de maximización o minimización?
Es un problema de minimización ya que es objetivo es minimizar el número total de actores convocados cada  día durante todas las sesiones de doblaje.
Ventajas:
- Llamar a menos actores por día va a reducir el coste de producción.
- Permite realizar más tomas con el mínimo número de actos disponibles por día.

Respuesta

Diseña un algoritmo para resolver el problema por fuerza bruta

In [1]:
# Fuerza Bruta para 6 tomas y 2 días
import numpy as np
import itertools

# Subconjunto de la matriz SESIONES (6 tomas x 10 actores)
SESIONES = np.array([
    [1,1,1,1,1,0,0,0,0,0],  # Toma  0: Actores: 0, 1, 2, 3, 4
    [0,0,1,1,1,0,0,0,0,0],  # Toma  1: Actores: 2, 3, 4
    [0,1,0,0,1,0,1,0,0,0],  # Toma  2: Actores: 1, 4, 6
    [1,1,0,0,0,0,1,1,0,0],  # Toma  3: Actores: 0, 1, 6, 7
    [0,1,0,1,0,0,0,1,0,0],  # Toma  4: Actores: 1, 3, 7
    [1,1,0,1,1,0,0,0,0,0],  # Toma  5: Actores: 0, 1, 3, 4
    [1,1,0,1,1,0,0,0,0,0],  # Toma  6: Actores: 0, 1, 3, 4
    [1,1,0,0,0,1,0,0,0,0],  # Toma  7: Actores: 0, 1, 5
    [1,1,0,1,0,0,0,0,0,0],  # Toma  8: Actores: 0, 1, 3
    [1,1,0,0,0,1,0,0,1,0],  # Toma  9: Actores: 0, 1, 5, 8
    [1,1,1,0,1,0,0,1,0,0],  # Toma 10: Actores: 0, 1, 2, 4, 7
    [1,1,1,1,0,1,0,0,0,0],  # Toma 11: Actores: 0, 1, 2, 3, 5
    [1,0,0,1,1,0,0,0,0,0],  # Toma 12: Actores: 0, 3, 4
    [1,0,1,0,0,1,0,0,0,0],  # Toma 13: Actores: 0, 2, 5
    [1,1,0,0,0,0,1,0,0,0],  # Toma 14: Actores: 0, 1, 6
    [0,0,0,1,0,0,0,0,0,1],  # Toma 15: Actores: 3, 9
    [1,0,1,0,0,0,0,0,0,0],  # Toma 16: Actores: 0, 2
    [0,0,1,0,0,1,0,0,0,0],  # Toma 17: Actores: 2, 5
    [1,0,1,0,0,0,0,0,0,0],  # Toma 18: Actores: 0, 2
    [1,0,1,1,1,0,0,0,0,0],  # Toma 19: Actores: 0, 2, 3, 4
    [0,0,0,0,0,1,0,1,0,0],  # Toma 20: Actores: 5, 7
    [1,1,1,1,0,0,0,0,0,0],  # Toma 21: Actores: 0, 1, 2, 3
    [1,0,1,0,0,0,0,0,0,0],  # Toma 22: Actores: 0, 2
    [0,0,1,0,0,1,0,0,0,0],  # Toma 23: Actores: 2, 5
    [1,1,0,1,0,0,0,0,0,1],  # Toma 24: Actores: 0, 1, 3, 9
    [1,0,1,0,1,0,0,0,1,0],  # Toma 25: Actores: 0, 2, 4, 8
    [0,0,0,1,1,0,0,0,0,0],  # Toma 26: Actores: 3, 4
    [1,0,0,1,0,0,0,0,0,0],  # Toma 27: Actores: 0, 3
    [1,0,0,0,1,1,0,0,0,0],  # Toma 28: Actores: 0, 4, 5
    [1,0,0,1,0,0,0,0,0,0],  # Toma 29: actores: 0, 3
])

SESIONES_REDUCIDA = SESIONES[:6] # Solo las 6 primeras porque es inviable aumentar

# Todas las particiones válidas de 6 tomas en 2 días de 3 tomas
tomas = list(range(6))
mejor_coste = float('inf')
mejor_asignacion = None

# Generar todas las combinaciones de 3 tomas para el primer día
for dia1 in itertools.combinations(tomas, 3):
    dia1 = set(dia1)
    dia2 = set(tomas) - dia1
    asignacion = [list(dia1), list(dia2)]

    # Calcular coste actor/día
    coste = 0
    for dia in asignacion:
        actores = set()
        for toma in dia:
            actores.update(np.where(SESIONES_REDUCIDA[toma] == 1)[0])
        coste += len(actores)

    if coste < mejor_coste:
        mejor_coste = coste
        mejor_asignacion = asignacion

# Mostrar resultado
print("[FUERZA BRUTA - PRUEBA CON 6 TOMAS]")
for i, dia in enumerate(mejor_asignacion):
    actores = set()
    for toma in dia:
        actores.update(np.where(SESIONES_REDUCIDA[toma] == 1)[0])
    print(f"Día {i+1}: Tomas {dia} Actores: {sorted(list(actores))} (Nº actores: {len(actores)})")
print(f"\nCoste total mínimo: {mejor_coste} actor/día")


[FUERZA BRUTA - PRUEBA CON 6 TOMAS]
Día 1: Tomas [0, 1, 5] Actores: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4)] (Nº actores: 5)
Día 2: Tomas [2, 3, 4] Actores: [np.int64(0), np.int64(1), np.int64(3), np.int64(4), np.int64(6), np.int64(7)] (Nº actores: 6)

Coste total mínimo: 11 actor/día


Calcula la complejidad del algoritmo por fuerza bruta

Respuesta:

El algoritmo por fuerza bruta explora **todas las asignaciones posibles** de 30 tomas a 6 días, cumpliendo que:
- Cada día tenga exactamente 6 tomas.
- Cada toma se asigne una sola vez.
- Se minimice el coste total actor/día.

El número total de particiones válidas del conjunto $\{0, \ldots, 29\}$ en 6 subconjuntos disjuntos de tamaño 6 es:

$$
\frac{30!}{(6!)^6} \approx 1.896 \times 10^{15}
$$

Cada solución se evalúa en tiempo constante $\mathcal{O}(1)$ porque:
- Hay 6 días.
- Cada día tiene 6 tomas como máximo.
- Cada toma tiene como mucho 10 actores.

Por tanto, la la **complejidad total** del algoritmo es: $$\mathcal{O}\left( \frac{30!}{(6!)^6} \right)$$

Esto lo hace **computacionalmente inviable** para 30 tomas.  
Solo puede utilizarse con instancias reducidas (por ejemplo, 6 u 8 tomas) como he puesto en el código para validación.

(*)Diseña un algoritmo que mejore la complejidad del algoritmo por fuerza bruta. Argumenta porque crees que mejora el algoritmo por fuerza bruta
Propongo el algoritmo de [Ramificación y Poda] para reducir el el nº de soluciones exploradas ya que no explora todas las soluciones, parte del espacio de soluciones de fuerza bruta, usa cotas inferiores para evitar recorrer ramas no prometedoras y; en el peor caso, puede ser igual de lento, pero en la práctica es mucho más eficiente.


In [4]:
import pandas as pd

# Subconjunto reducido de la matriz SESIONES para 6 tomas y 10 actores
SESIONES_REDUCIDA = np.array([
    [1, 0, 1, 0, 1, 0, 0, 1, 0, 0],
    [0, 1, 0, 1, 0, 0, 1, 0, 0, 1],
    [1, 1, 0, 0, 0, 1, 1, 0, 0, 0],
    [0, 0, 1, 1, 0, 0, 0, 0, 1, 1],
    [1, 0, 0, 0, 1, 1, 0, 1, 0, 0],
    [0, 1, 1, 0, 0, 0, 1, 0, 1, 0]
])

MAX_TOMAS = 6
MAX_TOMAS_DIA = 3
MAX_DIAS = 2
NUM_ACTORES = 10

mejor_coste = float('inf')
mejor_solucion = None

def coste(solucion, sesiones):
    total = 0
    for dia in solucion:
        actores = set()
        for toma in dia:
            actores.update(np.where(sesiones[toma] == 1)[0])
        total += len(actores)
    return total

def ramificacion_y_poda(solucion_parcial, tomas_disponibles, sesiones):
    global mejor_coste, mejor_solucion
    if not tomas_disponibles:
        c = coste(solucion_parcial, sesiones)
        if c < mejor_coste:
            mejor_coste = c
            mejor_solucion = [list(d) for d in solucion_parcial]
        return

    toma = tomas_disponibles[0]
    for i in range(MAX_DIAS):
        if len(solucion_parcial[i]) < MAX_TOMAS_DIA:
            solucion_parcial[i].append(toma)

            cota = coste(solucion_parcial, sesiones)
            if cota < mejor_coste:
                ramificacion_y_poda(solucion_parcial, tomas_disponibles[1:], sesiones)

            solucion_parcial[i].pop()

# Ejecutar
sol_inicial = [[] for _ in range(MAX_DIAS)]
ramificacion_y_poda(sol_inicial, list(range(MAX_TOMAS)), SESIONES_REDUCIDA)

# Mostrar resultados
resultado = []
for i, dia in enumerate(mejor_solucion):
    actores = set()
    for toma in dia:
        actores.update(np.where(SESIONES_REDUCIDA[toma] == 1)[0])
    resultado.append({
        "DÍA": i + 1,
        "TOMAS ASIGNADAS": dia,
        "ACTORES CONVOCADOS": sorted(list(actores)),
        "Nº ACTORES": len(actores)
    })

df_rp = pd.DataFrame(resultado)
print("\n[RESULTADO RAMIFICACIÓN Y PODA (6 TOMAS)]")
print(df_rp.to_string(index=False))
print(f"\nCoste total mínimo: {mejor_coste} actores/día")



[RESULTADO RAMIFICACIÓN Y PODA (6 TOMAS)]
 DÍA TOMAS ASIGNADAS    ACTORES CONVOCADOS  Nº ACTORES
   1       [0, 2, 4] [0, 1, 2, 4, 5, 6, 7]           7
   2       [1, 3, 5]    [1, 2, 3, 6, 8, 9]           6

Coste total mínimo: 13 actores/día


(*) Calcula la complejidad del algoritmo

El algoritmo de Ramificación y Poda explora un árbol de decisiones en el que cada nivel representa la asignación de una toma a un día, y aplica poda para eliminar ramas no prometedoras.
Si no hubiera poda, cada una de las $n = 30$ tomas podría asignarse a uno de los 6 días:
$$
\text{Nº de nodos sin poda} \leq 6^{30}
$$

Esto es una complejidad exponencial inasumible.

Se podan ramas del árbol cuando:
- Se supera el límite de 6 tomas por día (es inviable a partir de ese número).
- La cota inferior del nodo actual es mayor o igual que la mejor solución conocida.

Esto reduce enormemente el número de nodos explorados en la práctica.

Complejidad:
**Peor caso (sin poda efectiva):** $$\mathcal{O}(6^n)\quad \text{donde } n = \text{nº de tomas}$$

**Mejor caso (con poda eficiente):**
  - Explora solo una pequeña fracción del árbol.
  - Solución óptima o casi óptima en tiempo razonable y más rápido que con fuerza bruta.

Aunque [Ramificación y Poda] tiene también complejidad exponencial en el peor caso, la utilización de poda basada en cotas permite resolver instancias que sería imposibles popr [Fuerza Bruta].

**Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorios**

In [5]:
def generar_matriz_sesiones(num_tomas, num_actores, min_actores, max_actores, seed):
    """
    Genera una matriz binaria SESIONES de tamaño (num_tomas x num_actores),
    donde cada fila representa una toma y cada columna representa un actor.

    Parámetros:
    - num_tomas: número total de tomas (filas de la matriz)
    - num_actores: número total de actores (columnas de la matriz)
    - min_actores: número mínimo de actores por toma
    - max_actores: número máximo de actores por toma
    - seed: semilla para datos aleatorios

    Retorna:
    - SESIONES: matriz binaria aleatoria de dimensiones (num_tomas x num_actores)
    """

    # Fijamos la semilla para obtener resultados
    np.random.seed(seed)

    # Inicializamos la matriz SESIONES con ceros (ningún actor participa aún)
    SESIONES = np.zeros((num_tomas, num_actores), dtype=int)

    # Para cada toma (fila), elegimos un número aleatorio de actores que participarán
    for toma in range(num_tomas):
        # Seleccionamos aleatoriamente entre min_actores y max_actores
        n_actores = np.random.randint(min_actores, max_actores + 1)

        # Elegimos 'n_actores' actores diferentes (sin repetición) de entre todos los disponibles
        actores_en_toma = np.random.choice(num_actores, size=n_actores, replace=False)

        # Asignamos un 1 en la matriz para indicar qué actores participan en esta toma
        SESIONES[toma, actores_en_toma] = 1

    return SESIONES

**Aplica el algoritmo al juego de datos generado**

In [6]:
# Generamos una matriz SESIONES aleatoria de 30 tomas y 10 actores
NUM_TOMAS = 30
NUM_ACTORES = 10
MIN_ACTORES = 2
MAX_ACTORES = 5
SEED = 42

SESIONES = generar_matriz_sesiones(
    num_tomas=NUM_TOMAS,
    num_actores=NUM_ACTORES,
    min_actores=MIN_ACTORES,
    max_actores=MAX_ACTORES,
    seed=SEED
)

# Mostrar las primeras filas de la matriz generada
print("Primeras 5 tomas de la matriz SESIONES:")
print(SESIONES[:5])

Primeras 5 tomas de la matriz SESIONES:
[[1 0 0 0 0 1 1 0 0 1]
 [1 1 0 0 0 0 1 0 1 1]
 [0 0 1 0 0 0 1 0 1 0]
 [0 1 0 0 1 1 0 0 1 0]
 [0 0 1 0 0 1 0 1 0 1]]


**Enumera las referencias que has utilizado(si ha sido necesario) para llevar a cabo el trabajo**

He tenido que mirar el material siguiente:
- Manual de la asignatura 'Algoritmos de Optimización' (para decidir qué algoritmos eran propios para resolver el problema).
- Manual de la asignatura 'Matemáticas para la IA' (para resolver lo referente a la combinatoria).
- Manual de la asignatura 'Python para la IA' (para resolver el código en python).
- Web de (numphy) https://numpy.org/ para maniputlación de matrices (modelo de datos de SESIONES, 'itertools' para las combinaciones por fuerza bruta y 'pandas' para visualizar las soluciones.

**Describe brevemente las lineas de cómo crees que es posible avanzar en el estudio del problema. Ten en cuenta incluso posibles variaciones del problema y/o variaciones al alza del tamaño**

El problema de organizar las sesiones de doblaje es un problema de asignación  con restricciones combinatorias ya comentadas anteriormente y su escalabilidad habería que analizarlo; por ejemplo, si se aumentase el número de tomas y de actores se podería evaluar el comportamiento de los algoritmos analizando cómo va creciendo la complejidad o se degrada la solución con las técnicas heurística y metaheurística.

Se podría desarrollar heurísticas híbridas que combinansen por ejemplo; GRASP + Búsqueda Tabú (ya incluido en el código este último).